```
Name - Andrea Fox
Date - July 22, 2020
Class - DSC550-T301
Assignment - Week 8 Exercises - Dimensionality Reduction & Neural Nets
```

# 1 - Dimensionality Reduction

### Part A)
```
Here is a table of 1-5 star ratings for five movies (M, N, P. Q. R) by three raters (A,B,C). 
Rater	M	N	P	Q	R
A	1	2	3	4	5
B	2	3	2	5	3
C	5	5	5	3	2
Normalize the ratings by subtracting the average for each row and then subtracting the average for each column in the resulting table.
```

In [28]:
#Load libraries for question 1
import pandas as pd
import numpy as np
import scipy.linalg as la

In [2]:
"""
Reference: https://gist.github.com/primaryobjects/0414cf64fe38f2eca1ee
Found this cheat sheet to get some of the R to Python: https://towardsdatascience.com/cheat-sheet-for-python-dataframe-r-dataframe-syntax-conversions-450f656b44ca
"""

#Create dataframe with information
m = {'M': [1,2,5], 
         'N': [2,3,5], 
         'P': [3,2,5], 
         'Q': [4,5,3], 
         'R': [5,3,2]}

movies = pd.DataFrame(m, index = ['A', 'B', 'C'])

#Preview dataframe
movies

M  N  P  Q  R
A  1  2  3  4  5
B  2  3  2  5  3
C  5  5  5  3  2

In [3]:
#Compute average for each row
movies.mean(axis = 1)

A    3.0
B    3.0
C    4.0
dtype: float64

In [4]:
#Subtract average of each forw from each value in row
df = movies.sub(movies.mean(axis = 1), axis = 0)
df

M    N    P    Q    R
A -2.0 -1.0  0.0  1.0  2.0
B -1.0  0.0 -1.0  2.0  0.0
C  1.0  1.0  1.0 -1.0 -2.0

In [5]:
#Compute average for each column
df.mean()

M   -0.666667
N    0.000000
P    0.000000
Q    0.666667
R    0.000000
dtype: float64

In [6]:
#Subtract mean of each column from each value in column
df = df.sub(df.mean(axis = 0), axis = 1)
df

M    N    P         Q    R
A -1.333333 -1.0  0.0  0.333333  2.0
B -0.333333  0.0 -1.0  1.333333  0.0
C  1.666667  1.0  1.0 -1.666667 -2.0

### Part B)
```
This is a table giving the profile of three items:
A	1	0	1	0	1	2
B	1	1	0	0	1	6
C	0	1	0	1	0	2
The first five attributes are Boolean, and the last is an integer "rating." Assume that the scale factor for the rating is α. Compute, as a function of α, the cosine distances between each pair of profiles. For each of α = 0, 0.5, 1, and 2, determine the cosine of the angle between each pair of vectors.
```

In [10]:
#Create arrays for each row
a = np.array([1,0,1,0,1,2])
b = np.array([1,1,0,0,1,6])
c = np.array([0,1,0,1,0,2])

#Create label for each row
rows = ['a','b', 'c']
labels = [a,b,c]

In [11]:
#Defining a cosine distance function that takes 2 inputs
def cosDist(x, y):
    return np.dot(x, y) / (np.sqrt(np.sum(np.power(x, 2))) * np.sqrt(np.sum(np.power(y, 2))))

#Defining weighted cosine that takes x, y, attr_index (attribute index), and alpha (weight to apply to target)
def weightcos(x, y, attr_index, alpha):
    a = np.copy(x)
    b = np.copy(y)
    
    if len(x) != len(y):
        print('Lengths do no match')
        return 0
    
    #Apply weights to attributes
    a[attr_index] = a[attr_index] * alpha
    b[attr_index] = b[attr_index] * alpha
    
    #Return cosDist with the weights
    return cosDist(a,b)

In [13]:
#Weights
index = 5
weights = [0,0.5,1,2]

#Printing out each angle cosine for each pair
for i, (r,l) in enumerate(zip(labels, rows)):
    for j in range(len(labels)):
        if i == j:
            next
        else:
            for w in weights:
                angle_cosine = weightcos(r, labels[j], index, w)
                print(f'{rows[i]} - {rows[j]} | {w:<3}: {round(angle_cosine,4)}')

a - b | 0  : 0.6667
a - b | 0.5: 0.7217
a - b | 1  : 0.8473
a - b | 2  : 0.9461
a - c | 0  : 0.0
a - c | 0.5: 0.2887
a - c | 1  : 0.6172
a - c | 2  : 0.8652
b - a | 0  : 0.6667
b - a | 0.5: 0.7217
b - a | 1  : 0.8473
b - a | 2  : 0.9461
b - c | 0  : 0.4082
b - c | 0.5: 0.6667
b - c | 1  : 0.8498
b - c | 2  : 0.9526
c - a | 0  : 0.0
c - a | 0.5: 0.2887
c - a | 1  : 0.6172
c - a | 2  : 0.8652
c - b | 0  : 0.4082
c - b | 0.5: 0.6667
c - b | 1  : 0.8498
c - b | 2  : 0.9526


### Part C)
```
In this question, all columns will be written in their transposed form, as rows, to make the typography simpler. Matrix M has three rows and two columns, and the columns form an orthonormal basis. One of the columns is [2/7,3/7,6/7]. There are many options for the second column [x,y,z]. Write down those constraints on x, y, and z. Then, identify in the list below the one column that could be [x,y,z]. All components are computed to three decimal places, so the constraints may be satisfied only to a close approximation.
```

In [ ]:
col1 = np.array([2/7, 3/7, 6/7])



### Part D)
```
Suppose we have three points in a two dimensional space: (1,1), (2,2), and (3,4). We want to perform PCA on these points, so we construct a 2-by-2 matrix whose eigenvectors are the directions that best represent these three points. Construct this matrix.
```

In [29]:
"""
Referenced: http://www.physics.utah.edu/~detar/lessons/python/numpy_eigen/node1.html for some of the information
"""
#Create an array for the points
x = np.array([[1,1], [2,2], [3,4]])
y = np.dot(x.transpose(), x)

#Setting eigenvalues and eigenvectors
eigvals, eigvecs = la.eig(y)

#Find eigenvectors
eigvecs

array([[-0.77512996, -0.63180182],
       [ 0.63180182, -0.77512996]])

In [30]:
#Find eigenvalues
eigvals.real

array([ 0.14344504, 34.85655496])

### Part E)
```
Identify the vector that is orthogonal to the vector [1,2,3].
```

In [31]:
"""
Referenced: https://www.youtube.com/watch?v=8t4qgEXKguw&feature=youtu.be
"""

v = np.array([1,2,3])

#If u = np.array([a,b,c]) we would have the following:
# v dot u = 
# 1 + 2 + 3c = 0
# 3 + 3c = 0
# 3c = -3
#c = -1
u = np.array([1,1,-1])
np.dot(v,u)

0

### Part F)
```
Consider the diagonal matrix M =

1	0	0
0	2	0
0	0	0
Compute its Moore-Penrose pseudoinverse.
```

In [15]:
#Create dataframe from matrix M
M = pd.DataFrame(np.array([[1, 0, 0], [0, 2, 0], [0, 0, 0]]))

#Compute Moore-Penrose pseudoinverse
np.linalg.pinv(M)

array([[1. , 0. , 0. ],
       [0. , 0.5, 0. ],
       [0. , 0. , 0. ]])

# 2 - Exercise 11.3.2 from the Mining of Massive Dataset text

```
Use the SVD from Fig. 11.7. Suppose Leslie assigns rating 3 to Alien and rating 4 to Titanic, giving us a representation of Leslie in "movie space" of [0,3,0,0,4]. Find the representation of Leslie in concept space. What does that representation predict about how well Leslie would like the other movies appearing in our example data?
```

In [16]:
#Import libraries
import pandas as pd
import numpy as np
from scipy.linalg import svd

In [17]:
#M from figure 11.7
M_main = np.array([[1,1,1,0,0],[3,3,3,0,0],[4,4,4,0,0],[5,5,5,0,0],[0,0,0,4,4],[0,0,0,5,5],[0,0,0,2,2]])
M_main

array([[1, 1, 1, 0, 0],
       [3, 3, 3, 0, 0],
       [4, 4, 4, 0, 0],
       [5, 5, 5, 0, 0],
       [0, 0, 0, 4, 4],
       [0, 0, 0, 5, 5],
       [0, 0, 0, 2, 2]])

In [18]:
#Leslie's 
M_Leslie = np.array([[1,1,1,0,0],[3,3,3,0,0],[4,4,4,0,0],
                   [5,5,5,0,0],[0,0,0,4,4],[0,0,0,5,5],
                   [0,0,0,2,2],[0,3,0,0,4]])

M_Leslie

array([[1, 1, 1, 0, 0],
       [3, 3, 3, 0, 0],
       [4, 4, 4, 0, 0],
       [5, 5, 5, 0, 0],
       [0, 0, 0, 4, 4],
       [0, 0, 0, 5, 5],
       [0, 0, 0, 2, 2],
       [0, 3, 0, 0, 4]])

In [20]:
#SVD
L_U, L_s, L_VT = svd(M_Leslie)
Uo, so, VTo = svd(M_main)

Leslie = np.array([0,3,0,0,4])
VTo

array([[-0.57735027, -0.57735027, -0.57735027, -0.        , -0.        ],
       [-0.        , -0.        , -0.        , -0.70710678, -0.70710678],
       [ 0.        ,  0.        ,  0.        , -0.70710678,  0.70710678],
       [ 0.        , -0.70710678,  0.70710678,  0.        ,  0.        ],
       [ 0.81649658, -0.40824829, -0.40824829,  0.        ,  0.        ]])

In [21]:
#Getting the rest of the matrixes from figure 11.7
U = np.array([[.14,0],
             [.42,0],
             [.56,0],
             [.70,0],
             [0,.60],
             [0,.75],
             [0,.30]
             ])

Sigma = np.array([[12.4,0],
                 [0,9.5]
                 ])

V_trans = np.array([[.58,.58,.58,0,0],
                    [0,0,0,.71,.71]])

V_trans

array([[0.58, 0.58, 0.58, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.71, 0.71]])

In [24]:
#To get Leslie in concept space, we multiply leslie's ratings with de-transposed V_trans matrix (p.430)
V = V_trans.transpose()

# calc dot product to get concept space
CS = np.dot(Leslie,V)
CS

array([1.74, 2.84])

In [25]:
#Determine how Leslie might feel about the other moves
np.dot(CS,V_trans)

array([1.0092, 1.0092, 1.0092, 2.0164, 2.0164])

In [26]:
#Leslie's ratings
Leslie

array([0, 3, 0, 0, 4])

```
The results show that Leslie is more likely to prefer Romance moves over others
```